apiVersion: v1
kind: Secret
metadata:
  name: fintrack-secrets
  namespace: fintrack
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2ZpbnRyYWNrX3VzZXI6ZmludHJhY2tfcGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9maW50cmFjaw==
  REDIS_URL: cmVkaXM6Ly9yZWRpczozNjM3OQ==
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJl
  JWT_REFRESH_SECRET: eW91ci1yZWZyZXNoLXNlY3JldC1rZXktaGVyZQ==
